masters:
    hosts:
        master:
            ansible_host: 167.71.233.70
            ansible_user: root

workers:
    hosts:
        worker1: 
            ansible_host: 165.22.220.101 
            ansible_user: root
        
        worker2:
            ansible_host: 165.22.220.39
            ansible_user: root

all:
    vars:
        ansible_python_interpreter: /usr/bin/python3